# Generated by Django 2.1.7 on 2019-10-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities',
                                    to='locations.District'),
        ),
        migrations.AlterField(
            model_name='subzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzones',
                                    to='locations.Zone'),
        ),
        migrations.AlterField(
            model_name='wing',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings',
                                    to='locations.Facility'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones',
                                    to='locations.Wing'),
        ),
    ]
