# Generated by Django 2.2.6 on 2020-01-18 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200107_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
