# Generated by Django 3.0.3 on 2020-03-27 16:30

from django.db import migrations


def gen_defaults(apps, schema_editor):
    LocationInstance = apps.get_model('locations', 'LocationInstance')

    for row in LocationInstance.objects.all():
        if not row.level:
            if row.subzone:
                row.level = 'subzone'
            elif row.zone:
                row.level = 'zone'
            elif row.wing:
                row.level = 'wing'
            elif row.facility:
                row.level = 'facility'
            elif row.district:
                row.level = 'district'
            elif row.region:
                row.level = 'region'
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_locationinstance_level'),
    ]

    operations = [
        migrations.RunPython(gen_defaults, reverse_code=migrations.RunPython.noop)
    ]
